### ISSUE TITLE
Installation doc is incomplete ?

### ISSUE THREAD

**Issue by laulaz** [cguardia/questions#26]
* Questions version: 0.5.0a2
* Python version: 3.7.0
* Operating System: Mac OS 10.13.6

### Description

I try to get the simple "Full Working Multi-page Flask Application" from README working.
`form.py` contains this code (in my example).

### What I Did

```
virtualenv-3.7 .
bin/pip install flask
bin/pip install questions
export FLASK_APP=form.py
bin/flask run
```
I needed to install `typing-extensions`, which is not in documentation and causes traceback at flask startup : `ModuleNotFoundError: No module named 'typing_extensions'`

```
bin/pip install typing-extensions
```

Then, flask can start, but accessing http://127.0.0.1:5000/ causes this traceback:
```
 * Serving Flask app "form.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2020-12-10 22:53:39,162] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/laurent/instances/questions/form.py", line 32, in form
    return form.render_html()
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/questions/form.py", line 376, in render_html
    survey_js = self.render_js(form_data=form_data)
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/questions/form.py", line 357, in render_js
    platform=self.platform,
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/questions/templates.py", line 123, in get_survey_js
    html_id=html_id,
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/questions/templates.py", line 28, in _render_template
    template = env.get_template(filename)
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/laurent/instances/questions/lib/python3.7/site-packages/jinja2/loaders.py", line 249, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: survey_js.jquery.jinja
127.0.0.1 - - [10/Dec/2020 22:53:39] "GET / HTTP/1.1" 500 -
```

What step is missing here to get this survey_js.jquery.jinja ?  I can help for completing the documentation ...

**Comment by cguardia** [comment]
Templates were not being included in the distribution. This is fixed in 0.5.0a3. Will update docs about typing_extensions. Thanks!
